# Generated by Django 5.0.6 on 2024-08-15 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repertoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=100)),
                ("show_date", models.CharField(max_length=10)),
                ("show_hour", models.CharField(max_length=5)),
                ("hall_number", models.IntegerField()),
                ("movie_description", models.CharField(max_length=300)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=1)),
                ("seat", models.IntegerField()),
                (
                    "repertoire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema.repertoire",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.user"
                    ),
                ),
            ],
        ),
    ]
