# Generated by Django 5.0.6 on 2024-09-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_movie_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinema.tickettype"
            ),
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
