# Generated by Django 5.0.6 on 2024-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(default='2024-08-28'),
        ),
    ]
