# Generated by Django 5.0.7 on 2024-09-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_tickettype_alter_reservation_price_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='room',
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_number', models.CharField(max_length=10)),
                ('cleaning_time', models.DurationField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seance',
            name='hall_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
