# Generated by Django 5.0.6 on 2024-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_seance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='hall_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seance',
            name='hour_start',
            field=models.TimeField(default='21:33'),
        ),
    ]
