# Generated by Django 5.0.7 on 2024-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_seattype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
