# Generated by Django 5.0.6 on 2024-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_seance_hour_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.AlterField(
            model_name='seance',
            name='hour_start',
            field=models.TimeField(),
        ),
    ]
