# Generated by Django 5.0.6 on 2024-09-08 10:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_rename_movie_movies_alter_seance_hour_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='hour_start',
        ),
        migrations.AddField(
            model_name='seance',
            name='show_start',
            field=models.DateTimeField(default=DateTime(2024, 9, 8, 10, 9, 53, 33694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seance',
            name='hall_number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='seance',
            table=None,
        ),
        migrations.AlterField(
            model_name='seance',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('cleaning_time', models.DurationField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('column', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('niedostępne', 'Niedostępne'), ('uszkodzone', 'Uszkodzone'), ('dostępne', 'Dostępne')], default='dostępne', max_length=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('seat', models.IntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.price')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
