# Generated by Django 5.0.7 on 2024-09-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_seat_rotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='hall_number',
            new_name='hall',
        ),
    ]
