# Generated by Django 5.0.7 on 2024-09-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_rename_hall_number_seance_hall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.tickettype'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.seance'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cinema.hall'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cinema.movie'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.hall'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cinema.seattype'),
        ),
        migrations.AlterField(
            model_name='seattype',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/icons/'),
        ),
    ]
