# Generated by Django 5.0.7 on 2024-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_hall_cinema_alter_reservation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
