# Generated by Django 5.0.7 on 2024-09-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_seat_column_seat_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cinema.reservationcollection'),
        ),
    ]
