# Generated by Django 5.0.7 on 2024-09-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_remove_reservation_user_reservationcollection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatreservation',
            old_name='price',
            new_name='ticket_type',
        ),
    ]
