# Generated by Django 5.0.7 on 2024-09-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_rename_price_reservation_ticket_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='SeatReservation',
        ),
    ]
