# Generated by Django 5.0.7 on 2024-09-14 22:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_rename_reservation_seatreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationCollection',
            new_name='Reservation',
        ),
    ]
