# Generated by Django 5.0.7 on 2024-09-14 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_rename_reservationcollection_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cinema.seance'),
        ),
    ]
