# Generated by Django 5.0.7 on 2024-09-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_reservation_seance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatreservation',
            old_name='collection',
            new_name='reservation',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='seance',
        ),
    ]
