# Generated by Django 5.0.7 on 2024-10-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_movie_poster'),
        ('cinema', '0018_reservation_cancelled_reservation_paid'),
    ]

    operations = [
    ]
