# Generated by Django 5.0.7 on 2024-11-02 15:41

import django.db.models.deletion
import pendulum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_merge_20241020_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='allowed_ticket_types',
            field=models.ManyToManyField(blank=True, to='cinema.tickettype'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seances', to='cinema.movie'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='show_start',
            field=models.DateTimeField(default=pendulum.now),
        ),
    ]
