# Generated by Django 5.0.7 on 2024-11-02 23:28

import django.db.models.deletion
import pendulum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_reservation_uuid_seattype_allowed_ticket_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
