# Generated by Django 5.0.7 on 2024-11-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_seattype_allowed_ticket_types_alter_seance_movie_and_more'),
        ('cinema', '0021_reservation_used_seattype_allowed_ticket_types_and_more'),
    ]

    operations = [
    ]
