# Generated by Django 5.0.7 on 2024-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_merge_20241103_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='extra_validation',
            field=models.BooleanField(default=True),
        ),
    ]
